version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6378:6379"
    networks:
      - app-network      

  worker:
    build: .
    container_name: worker
    ports:
      - "3002:3002"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app-network
    dns:
      - 8.8.8.8

networks:
  app-network:
    driver: bridge
    # external: true